# Generated by Django 4.1.3 on 2023-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_menu_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(),
        ),
    ]
